services:
  react-app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--openssl-legacy-provider
    stdin_open: true
    tty: true
